#!/usr/bin/sh
# Script to process data and output temperature contour (and other stuff that I don't use). The temperature contour is output in a different format to the original codes implementation (t,x,y,T).

mv $1 results/
cd results/
ls > ../event_names.dat

for f in */
do
    cd $f
    mkdir results
    mv *.dat ./results/
    cp ../../../hydro_analysis.e ./hydro_analysis.e
    cp ../../../parameters.dat ./parameters.dat
    ./hydro_analysis.e
    cd ..
done


