#!/usr/bin/env sh
# Script to process data and output temperature contour (and other stuff that I don't use).
# The temperature contour is output in a different format to the original code's implementation (t,x,y,T).

codeDir=$(pwd)

input="$1"
inputAbs=$(realpath "$input") # Get absolute path of input directory
bn=$(basename "$input")

cd "$(dirname "$inputAbs")" || exit 1

mv "$bn" results/
mkdir "$bn"
mv results "$bn/"

cd "$bn/results" || exit 1
ls > ../event_names.dat

for f in */; do
    cd "$f" || continue
    mkdir -p results
    mv *.dat results/
    cp "$codeDir/hydro_analysis.e" .
    cp "$codeDir/parameters.dat" .
    ./hydro_analysis.e
    rm hydro_analysis.e
    cd ..
done